// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAumqW5uDFtAusdSnmuqq7FeJQHo2Neo6w',
    appId: '1:1088976238501:web:fda3e3b9193b3ed7dd5a4c',
    messagingSenderId: '1088976238501',
    projectId: 'homehunt-70ba1',
    authDomain: 'homehunt-70ba1.firebaseapp.com',
    storageBucket: 'homehunt-70ba1.appspot.com',
    measurementId: 'G-WW0HT05VNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxqFEUvfrEP5bkkEC4FkQGbxph9m5W1Ds',
    appId: '1:1088976238501:android:86bf6f05847ff132dd5a4c',
    messagingSenderId: '1088976238501',
    projectId: 'homehunt-70ba1',
    storageBucket: 'homehunt-70ba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2GI00m1XBYnf6a-8BYMURhD4Sk_OVBxg',
    appId: '1:1088976238501:ios:31191488f721d6c8dd5a4c',
    messagingSenderId: '1088976238501',
    projectId: 'homehunt-70ba1',
    storageBucket: 'homehunt-70ba1.appspot.com',
    iosBundleId: 'com.example.homehunt',
  );
}
